;(function(){var dfltPluginCfg={"sourceFile":"download","info":true};var dfltGlobalCfg={"site":0,"log":"","logSSL":"","domain":"","collectDomain":"logc406.xiti.com","collectDomainSSL":"logs1406.xiti.com","secure":true,"pixelPath":"/hit.xiti","disableCookie":false,"cookieSecure":true,"cookieDomain":"rbb-online.de","preview":false,"plgs":["Clicks","ClientSideUserId","ContextVariables","Page"],"lazyLoadingPath":"","documentLevel":"document","redirect":false,"activateCallbacks":true,"medium":"","ignoreEmptyChapterValue":false,"base64Storage":false};(function(a){a.ATInternet=a.ATInternet||{};a.ATInternet.Tracker=a.ATInternet.Tracker||{};a.ATInternet.Tracker.Plugins=a.ATInternet.Tracker.Plugins||{}})(window);
var Utils=function(){function a(b){var d=typeof b;if("object"!==d||null===b)return"string"===d&&(b='"'+b+'"'),String(b);var c,f,g=[],n=b&&b.constructor===Array;for(c in b)b.hasOwnProperty(c)&&(f=b[c],d=typeof f,"function"!==d&&"undefined"!==d&&("string"===d?f='"'+f.replace(/[^\\]"/g,'\\"')+'"':"object"===d&&null!==f&&(f=a(f)),g.push((n?"":'"'+c+'":')+String(f))));return(n?"[":"{")+String(g)+(n?"]":"}")}function e(a){return null===a?"":(a+"").replace(q,"")}function h(a){var d,c=null;return(a=e(a+""))&&
!e(a.replace(m,function(a,g,n,r){d&&g&&(c=0);if(0===c)return a;d=n||g;c+=!r-!n;return""}))?Function("return "+a)():null}var b=this,m=/(,)|(\[|{)|(}|])|"(?:[^"\\\r\n]|\\["\\\/bfnrt]|\\u[\da-fA-F]{4})*"\s*:?|true|false|null|-?(?!0\d)\d+(?:\.\d+|)(?:[eE][+-]?\d+|)/g,q=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g");b.Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(a){var d="",c,f,g,n,r,k,m=0;for(a=b.Base64._utf8_encode(a);m<
a.length;)c=a.charCodeAt(m++),f=a.charCodeAt(m++),g=a.charCodeAt(m++),n=c>>2,c=(c&3)<<4|f>>4,r=(f&15)<<2|g>>6,k=g&63,isNaN(f)?r=k=64:isNaN(g)&&(k=64),d=d+this._keyStr.charAt(n)+this._keyStr.charAt(c)+this._keyStr.charAt(r)+this._keyStr.charAt(k);return d},decode:function(a){var d="",c,f,g,n,r,k=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");k<a.length;)c=this._keyStr.indexOf(a.charAt(k++)),f=this._keyStr.indexOf(a.charAt(k++)),n=this._keyStr.indexOf(a.charAt(k++)),r=this._keyStr.indexOf(a.charAt(k++)),
c=c<<2|f>>4,f=(f&15)<<4|n>>2,g=(n&3)<<6|r,d+=String.fromCharCode(c),64!=n&&(d+=String.fromCharCode(f)),64!=r&&(d+=String.fromCharCode(g));return d=b.Base64._utf8_decode(d)},_utf8_encode:function(a){a=a.replace(/\r\n/g,"\n");for(var d="",c=0;c<a.length;c++){var f=a.charCodeAt(c);128>f?d+=String.fromCharCode(f):(127<f&&2048>f?d+=String.fromCharCode(f>>6|192):(d+=String.fromCharCode(f>>12|224),d+=String.fromCharCode(f>>6&63|128)),d+=String.fromCharCode(f&63|128))}return d},_utf8_decode:function(a){for(var d=
"",c=0,f,g,n;c<a.length;)f=a.charCodeAt(c),128>f?(d+=String.fromCharCode(f),c++):191<f&&224>f?(g=a.charCodeAt(c+1),d+=String.fromCharCode((f&31)<<6|g&63),c+=2):(g=a.charCodeAt(c+1),n=a.charCodeAt(c+2),d+=String.fromCharCode((f&15)<<12|(g&63)<<6|n&63),c+=3);return d}};b.loadScript=function(a,d){var c;d=d||function(){};c=document.createElement("script");c.type="text/javascript";c.src=a.url;c.async=!1;c.defer=!1;c.onload=c.onreadystatechange=function(a){a=a||window.event;if("load"===a.type||/loaded|complete/.test(c.readyState)&&
(!document.documentMode||9>document.documentMode))c.onload=c.onreadystatechange=c.onerror=null,d(null,a)};c.onerror=function(a,n,f){c.onload=c.onreadystatechange=c.onerror=null;d({msg:"script not loaded",event:a})};var f=document.head||document.getElementsByTagName("head")[0];f.insertBefore(c,f.lastChild)};b.cloneSimpleObject=function d(a,f){if("object"!==typeof a||null===a||a instanceof Date)return a;var g=new a.constructor,n;for(n in a)a.hasOwnProperty(n)&&(void 0===n||f&&void 0===a[n]||(g[n]=d(a[n])));
return g};b.jsonSerialize=function(d){try{return"undefined"!==typeof JSON&&JSON.stringify?JSON.stringify(d):a(d)}catch(c){return null}};b.jsonParse=function(a){try{return"undefined"!==typeof JSON&&JSON.parse?JSON.parse(a+""):h(a)}catch(c){return null}};b.arrayIndexOf=function(a,c){return Array.indexOf?a.indexOf(c):function(a){if(null==this)throw new TypeError;var c=Object(this),d=c.length>>>0;if(0===d)return-1;var r=0;1<arguments.length&&(r=Number(arguments[1]),r!=r?r=0:0!=r&&Infinity!=r&&-Infinity!=
r&&(r=(0<r||-1)*Math.floor(Math.abs(r))));if(r>=d)return-1;for(r=0<=r?r:Math.max(d-Math.abs(r),0);r<d;r++)if(r in c&&c[r]===a)return r;return-1}.apply(a,[c])};b.uuid=function(){return{v4:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var c=16*Math.random()|0;return("x"===a?c:c&3|8).toString(16)})},num:function(a){var c=new Date,f=function(a){a-=100*Math.floor(a/100);return 10>a?"0"+a:String(a)};return f(c.getHours())+""+f(c.getMinutes())+""+f(c.getSeconds())+""+
function(a){return Math.floor((9*Math.random()+1)*Math.pow(10,a-1))}(a-6)}}};b.getObjectKeys=function(a){var c=[],f;for(f in a)a.hasOwnProperty(f)&&c.push(f);return c};b.completeFstLevelObj=function(a,c,f){if(a){if(c)for(var g in c)!c.hasOwnProperty(g)||a[g]&&!f||(a[g]=c[g])}else a=c;return a};b.isPreview=function(){return window.navigator&&"preview"===window.navigator.loadPurpose};b.isPrerender=function(a){var c,f=!1,g=["webkit","ms"];if("prerender"===document.visibilityState)c="visibilitychange";
else for(var n=0;n<g.length;n++)"prerender"===document[g[n]+"VisibilityState"]&&(c=g[n]+"visibilitychange");if("undefined"!==typeof c){var r=function(g){a(g);b.removeEvtListener(document,c,r)};b.addEvtListener(document,c,r);f=!0}return f};var l=b.addEvtListener=function(a,c,f){a.addEventListener?a.addEventListener(c,f,!1):a.attachEvent&&a.attachEvent("on"+c,f)},k=b.removeEvtListener=function(a,c,f){a.removeEventListener?a.removeEventListener(c,f,!1):a.detachEvent&&a.detachEvent("on"+c,f)};b.hashcode=
function(a){var c=0;if(0===a.length)return c;for(var f=0;f<a.length;f++)var g=a.charCodeAt(f),c=(c<<5)-c+g,c=c|0;return c};b.setLocation=function(a){var c=a.location;a=window[a.target]||window;c&&(a.location.href=c)};b.dispatchCallbackEvent=function(a){var c;if("function"===typeof window.Event)c=new Event("ATCallbackEvent");else try{c=document.createEvent("Event"),c.initEvent&&c.initEvent("ATCallbackEvent",!0,!0)}catch(f){}c&&"function"===typeof document.dispatchEvent&&(c.name=a,document.dispatchEvent(c))};
b.addCallbackEvent=function(a){l(document,"ATCallbackEvent",a)};(function(){function a(c,d){d=d||{bubbles:!1,cancelable:!1,detail:void 0};var g;try{g=document.createEvent("CustomEvent"),g.initCustomEvent(c,d.bubbles,d.cancelable,d.detail)}catch(n){}return g}if("function"===typeof window.CustomEvent)return window.ATCustomEvent=window.CustomEvent,!1;a.prototype=window.Event.prototype;window.ATCustomEvent=a})();b.addOptOutEvent=function(a,c){b.ATOptOutEvent=new ATCustomEvent("ATOptOutEvent",{detail:{name:"clientsideuserid",
id:c}});l(document,"ATOptOutEvent",a)};b.removeOptOutEvent=function(a){k(document,"ATOptOutEvent",a)};b.dispatchOptOutEvent=function(a){b.optedOut=a;b.ATOptOutEvent=b.ATOptOutEvent||new ATCustomEvent("ATOptOutEvent",{detail:{name:"clientsideuserid",id:-1}});try{document.dispatchEvent(b.ATOptOutEvent)}catch(c){}};b.userOptedOut=function(){b.dispatchOptOutEvent(!0)};b.userOptedIn=function(){b.dispatchOptOutEvent(!1)};b.isOptedOut=function(){if(null===b.optedOut){var a;a:{if(a=(a=/(?:^| )atoptedout=([^;]+)/.exec(document.cookie)||
null)?decodeURIComponent(a[1]):null)if(a=b.jsonParse(a)||b.jsonParse(b.Base64.decode(a))){a=!!a.val;break a}a=!1}b.optedOut=a}return!!b.optedOut};b.optedOut=null;b.ATOptOutEvent=null};window.ATInternet.Utils=new Utils;
var BuildManager=function(a){var e=this,h=function(a,d,c){a="&"+a+"=";return{param:a,paramSize:a.length,str:d,strSize:d.length,truncate:c}},b=function(b,d){var c="",f=0,g=!0,n;for(n in b)if(b.hasOwnProperty(n)){var r=b[n];if(r){var g=!1,k=d-f;if(r.strSize+r.paramSize<k)c+=r.param+r.str,f+=r.strSize+r.paramSize,b[n]=void 0,g=!0;else{r.truncate?(c+=r.param+r.str.substr(0,k),b[n].str=r.str.substr(k,r.strSize-1),b[n].strSize=b[n].str.length):r.strSize+r.paramSize>d&&(a.emit("Tracker:Hit:Build:Error",
{lvl:"ERROR",msg:'Too long parameter "'+r.param+'"',details:{value:r.str}}),b[n].str=b[n].str.substr(0,d-r.paramSize-1),b[n].strSize=b[n].str.length);break}}else g=!0}return[c,g?null:b]},m=["ati","atc","pdtl","stc","dz"],q=function(k,d,c){var f=function(a){if(a==={})return"";var c=[],g;g={};var d=0,n=!1,f=void 0,k,e,p;for(p in a)if(a.hasOwnProperty(p)){var l=a[p].value;"function"===typeof l&&(l=l());l=l instanceof Array?l.join(a[p].options.separator||","):"object"===typeof l?window.ATInternet.Utils.jsonSerialize(l):
"undefined"===typeof l?"undefined":l.toString();a[p].options.encode&&(l=encodeURIComponent(l));var q=h(p,l,-1<window.ATInternet.Utils.arrayIndexOf(m,p)),d=d+(q.paramSize+q.strSize);if(a[p].options.last)1490<l.length&&l.substr(0,1490),k=p,e=q;else if(g[p]=q,1500<g[p].paramSize+g[p].strSize&&!g[p].truncate){n=!0;f=p;break}}k&&(g[k]=e);g=[g,d,n,f];a=g[0];if(g[2])g=g[3],a=a[g],a.str=a.str.substr(0,1450),a.strSize=1450,d={},d.mherr=h("mherr","1",!1),d[g]=a,c.push(b(d,1500)[0]);else if(g=b(a,1500),null===
g[1])c=g[0];else for(c.push(g[0]);null!==g[1];)g=b(a,1500),c.push(g[0]);return c},g="";a.buffer.presentInFilters(d,"hitType")||(d=a.buffer.addInFilters(d,"hitType",["page"]));d=a.buffer.addInFilters(d,"hitType",["all"]);var n;if(k){d=a.buffer.addInFilters(d,"permanent",!0);d=a.buffer.get(d,!0);for(n in k)k.hasOwnProperty(n)&&(d[n]={value:k[n],options:{}});g=f(d)}else for(n in d=a.buffer.get(d,!0),g=f(d),d)d.hasOwnProperty(n)&&!d[n].options.permanent&&a.buffer.del(n);c&&c(g)},l=function(b){var d=a.getConfig("secure"),
c="https:"===document.location.protocol,f=d||c,c="",c=f?a.getConfig("logSSL"):a.getConfig("log"),g=a.getConfig("domain"),c=c&&g?c+"."+g:f?a.getConfig("collectDomainSSL"):a.getConfig("collectDomain"),f=a.getConfig("baseURL");(g=a.getConfig("pixelPath"))&&"/"!==g.charAt(0)&&(g="/"+g);var n=a.getConfig("site");(f||c&&g)&&n?b&&b(null,(f?f:(d?"https://":"//")+c+g)+("?s="+n)):b&&b({message:"Config error"})},k=function(a,d,c){l(function(f,g){f?c&&c(f):q(a,d,function(a){var d=[],f=ATInternet.Utils.uuid().num(13);
if(a instanceof Array)if(1===a.length)d.push(g+"&mh=1-2-"+f+a[0]);else for(var b=1;b<=a.length;b++)d.push(g+"&mh="+b+"-"+a.length+"-"+f+a[b-1]);else d.push(g+a);c&&c(null,d)})})};e.send=function(b,d,c){k(b,d,function(d,g){if(d)a.emit("Tracker:Hit:Build:Error",{lvl:"ERROR",msg:d.message,details:{hits:g}});else for(var n=0;n<g.length;n++)e.sendUrl(g[n],c)})};e.sendUrl=function(b,d){var c=function(c,b){return function(){return function(f){a.emit(c,{lvl:-1===c.indexOf("Error")?"INFO":"ERROR",details:{hit:b,
event:f}});d&&d()}}()},f=new Image;f.onload=c("Tracker:Hit:Sent:Ok",b);f.onerror=c("Tracker:Hit:Sent:Error",b);f.src=b}},TriggersManager=function(){function a(a,b,l){for(var k=[],e=0;e<a.length;e++)a[e].callback(b,l),a[e].singleUse||k.push(a[e]);return k}function e(a,b,l,k){var p=a.shift();if("*"===p)return b["*"]=b["*"]||[],b["*"].push({callback:l,singleUse:k}),b["*"].length-1;if(0===a.length)return e([p,"*"],b,l,k);b["*"]=b["*"]||[];b[p]=b[p]||{};return e(a,b[p],l,k)}function h(b,e,l,k){var p=e.shift();
"*"!==p&&(0===e.length?h(b,[p,"*"],l,k):l[p]&&(l[p]["*"]=a(l[p]["*"],b,k),h(b,e,l[p],k)))}var b={};this.on=function(a,q,l){l=l||!1;return e(a.split(":"),b,q,l)};this.emit=function(m,e){b["*"]&&(b["*"]=a(b["*"],m,e));h(m,m.split(":"),b,e)}},PluginsManager=function(a){var e={},h={},b=0,m={},q=0,l=this.unload=function(c){e[c]?(e[c]=void 0,a.emit("Tracker:Plugin:Unload:"+c+":Ok",{lvl:"INFO"})):a.emit("Tracker:Plugin:Unload:"+c+":Error",{lvl:"ERROR",msg:"not a known plugin"});return a},k=this.load=function(c,
g){"function"===typeof g?"undefined"===typeof a.getConfig.plgAllowed||0===a.getConfig.plgAllowed.length||-1<a.getConfig.plgAllowed.indexOf(c)?(e[c]=new g(a),h[c]&&e[c]&&(h[c]=!1,b--,e[c+"_ll"]&&l(c+"_ll"),0===b&&a.emit("Tracker:Plugin:Lazyload:File:Complete",{lvl:"INFO",msg:"LazyLoading triggers are finished"})),a.emit("Tracker:Plugin:Load:"+c+":Ok",{lvl:"INFO"})):a.emit("Tracker:Plugin:Load:"+c+":Error",{lvl:"ERROR",msg:"Plugin not allowed",details:{}}):a.emit("Tracker:Plugin:Load:"+c+":Error",{lvl:"ERROR",
msg:"not a function",details:{obj:g}});return a},p=this.isLazyloading=function(a){return a?!0===h[a]:0!==b},d=function(a){return!e[a]&&!p(a)&&(e[a+"_ll"]?!0:!1)},c=function(c){h[c]=!0;b++;ATInternet.Utils.loadScript({url:a.getConfig("lazyLoadingPath")+c+".js"})},f=function(a){return d(a)?(c(a),!0):!1},g=function(a){m[a]?m[a]++:m[a]=1;q++};this.isExecWaitingLazyloading=function(){return 0!==q};a.exec=this.exec=function(b,f,k,l){var h=null,s=function(a,c,g,d){c=c.split(".");e[a]&&e[a][c[0]]&&(h=1<c.length&&
e[a][c[0]][c[1]]?e[a][c[0]][c[1]].apply(e[a],g):e[a][c[0]].apply(e[a],g));d&&d(h)},v=function(c,d,b,f){g(c);a.onTrigger("Tracker:Plugin:Load:"+c+":Ok",function(){s(c,d,b,function(g){m[c]--;q--;0===q&&a.emit("Tracker:Plugin:Lazyload:Exec:Complete",{lvl:"INFO",msg:"All exec waiting for lazyloading are done"});f&&f(g)})},!0)};d(b)?(v(b,f,k,l),c(b)):p(b)?v(b,f,k,l):s(b,f,k,l)};this.waitForDependencies=function(c,g){var d=function(a){for(var c={mcount:0,plugins:{}},g=0;g<a.length;g++)e.hasOwnProperty(a[g])||
(c.mcount++,c.plugins[a[g]]=!0);return c}(c);if(0===d.mcount)a.emit("Tracker:Plugin:Dependencies:Loaded",{lvl:"INFO",details:{dependencies:c}}),g();else for(var b in d.plugins)d.plugins.hasOwnProperty(b)&&(a.emit("Tracker:Plugin:Dependencies:Error",{lvl:"WARNING",msg:"Missing plugin "+b}),a.onTrigger("Tracker:Plugin:Load:"+b,function(a,c){var b=a.split(":"),f=b[3];"Ok"===b[4]&&(d.plugins[f]=!1,d.mcount--,0===d.mcount&&g())},!0),f(b))};this.init=function(){for(var a in ATInternet.Tracker.pluginProtos)ATInternet.Tracker.pluginProtos.hasOwnProperty(a)&&
k(a,ATInternet.Tracker.pluginProtos[a])}},CallbacksManager=function(a){var e={},h=this.load=function(b,m){"function"===typeof m?(new m(a),a.emit("Tracker:Callback:Load:"+b+":Ok",{lvl:"INFO",details:{obj:m}})):a.emit("Tracker:Callback:Load:"+b+":Error",{lvl:"ERROR",msg:"not a function",details:{obj:m}});return a};this.init=function(){if(a.getConfig("activateCallbacks")){var b=a.getConfig("callbacks");(function(){if("undefined"!==typeof b&&b.include instanceof Array)for(var a=0;a<b.include.length;a++)ATInternet.Callbacks&&
ATInternet.Callbacks.hasOwnProperty(b.include[a])&&(e[b.include[a]]={"function":ATInternet.Callbacks[b.include[a]]},ATInternet.Tracker.callbackProtos[b.include[a]]||(ATInternet.Tracker.callbackProtos[b.include[a]]=e[b.include[a]]));else for(a in ATInternet.Callbacks)ATInternet.Callbacks.hasOwnProperty(a)&&(e[a]={"function":ATInternet.Callbacks[a]},ATInternet.Tracker.callbackProtos[a]||(ATInternet.Tracker.callbackProtos[a]=e[a]));if("undefined"!==typeof b&&b.exclude instanceof Array)for(a=0;a<b.exclude.length;a++)e[b.exclude[a]]&&
(e[b.exclude[a]]=void 0);for(var q in e)e.hasOwnProperty(q)&&e[q]&&h(q,e[q]["function"])})();ATInternet.Utils.addCallbackEvent(function(a){if(a.name){var e=!0;"undefined"!==typeof b&&(b.include instanceof Array&&-1===ATInternet.Utils.arrayIndexOf(b.include,a.name)&&(e=!1),b.exclude instanceof Array&&-1!==ATInternet.Utils.arrayIndexOf(b.exclude,a.name)&&(e=!1));if(ATInternet.Callbacks&&ATInternet.Callbacks.hasOwnProperty(a.name)){var l={};l[a.name]={"function":ATInternet.Callbacks[a.name]};e&&h(a.name,
l[a.name]["function"]);ATInternet.Tracker.callbackProtos[a.name]||(ATInternet.Tracker.callbackProtos[a.name]=l[a.name])}}})}}},BufferManager=function(a){var e={};this.set=function(a,b,l){l=l||{};l.hitType=l.hitType||["page"];e[a]={value:b,options:l}};var h=function(a,b,e){return(a=window.ATInternet.Utils.cloneSimpleObject(a[b]))&&!e?a.value:a},b=function q(a,b){if(!(a&&b instanceof Array&&a instanceof Array))return[];if(0===a.length)return b;var p=a[0],d,c=[],f=window.ATInternet.Utils.cloneSimpleObject(a);
f.shift();for(var g=0;g<b.length;g++)if("object"!==typeof p[1])e[b[g]]&&e[b[g]].options[p[0]]===p[1]&&c.push(b[g]);else{d=p[1].length;for(var n=0;n<d;n++)if(e[b[g]]&&e[b[g]].options[p[0]]instanceof Array&&0<=window.ATInternet.Utils.arrayIndexOf(e[b[g]].options[p[0]],p[1][n])){c.push(b[g]);break}}return q(f,c)};this.get=function(a,l){var k={};if("string"===typeof a)k=h(e,a,l);else for(var p=b(a,window.ATInternet.Utils.getObjectKeys(e)),d=0;d<p.length;d++)k[p[d]]=h(e,p[d],l);return k};this.presentInFilters=
function l(a,b){return a&&0!==a.length?a[0][0]===b?!0:l(a.slice(1),b):!1};this.addInFilters=function k(a,d,c,b){if(!a||0===a.length)return b?[]:[[d,c]];var g=a[0][0],n=a[0][1];g===d&&(n instanceof Array&&!(-1<window.ATInternet.Utils.arrayIndexOf(n,c[0]))&&n.push(c[0]),b=!0);return[[g,n]].concat(k(a.slice(1),d,c,b))};this.del=function(a){e[a]=void 0};this.clear=function(){e={}}},Tag=function(a,e,h){e=e||{};var b=this;b.version="5.13.3";var m=window.ATInternet.Utils.cloneSimpleObject(e);b.triggers=
new TriggersManager(b);b.emit=b.triggers.emit;b.onTrigger=b.triggers.on;var q=window.ATInternet.Utils.cloneSimpleObject(dfltGlobalCfg)||{},l;for(l in a)a.hasOwnProperty(l)&&(q[l]=a[l]);b.getConfig=function(a){return q[a]};b.setConfig=function(a,e,d){void 0!==q[a]&&d||(b.emit("Tracker:Config:Set:"+a,{lvl:"INFO",details:{bef:q[a],aft:e}}),q[a]=e)};b.configPlugin=function(a,e,d){q[a]=q[a]||{};for(var c in e)e.hasOwnProperty(c)&&void 0===q[a][c]&&(q[a][c]=e[c]);d&&(d(q[a]),b.onTrigger("Tracker:Config:Set:"+
a,function(a,c){d(c.details.aft)}));return q[a]};b.getContext=function(a){return m[a]};b.setContext=function(a,e){b.emit("Tracker:Context:Set:"+a,{lvl:"INFO",details:{bef:m[a],aft:e}});m[a]=e};b.delContext=function(a,e){b.emit("Tracker:Context:Deleted:"+a+":"+e,{lvl:"INFO",details:{key1:a,key2:e}});if(a)m.hasOwnProperty(a)&&(e?m[a]&&m[a].hasOwnProperty(e)&&(m[a][e]=void 0):m[a]=void 0);else if(e)for(var d in m)m.hasOwnProperty(d)&&m[d]&&m[d].hasOwnProperty(e)&&(m[d][e]=void 0)};b.plugins=new PluginsManager(b);
b.buffer=new BufferManager(b);b.setParam=b.buffer.set;b.getParams=function(a){return b.buffer.get(a,!1)};b.getParam=b.buffer.get;b.delParam=b.buffer.del;b.builder=new BuildManager(b);b.sendHit=b.builder.send;b.sendUrl=b.builder.sendUrl;b.callbacks=new CallbacksManager(b);b.setParam("ts",function(){return(new Date).getTime()},{permanent:!0,hitType:["all"]});b.getConfig("disableCookie")&&b.setParam("idclient","Consent-NO",{permanent:!0,hitType:["all"]});b.getConfig("medium")&&b.setParam("medium",b.getConfig("medium"),
{permanent:!0,hitType:["all"]});b.plugins.init();b.callbacks.init();ATInternet.Tracker.instances.push(b);b.emit("Tracker:Ready",{lvl:"INFO",msg:"Tracker initialized",details:{tracker:b,args:{config:a,context:e,callback:h}}});h&&h(b)};ATInternet.Tracker.Tag=Tag;ATInternet.Tracker.instances=[];ATInternet.Tracker.pluginProtos={};
ATInternet.Tracker.addPlugin=function(a,e){e=e||ATInternet.Tracker.Plugins[a];if(!ATInternet.Tracker.pluginProtos[a]){ATInternet.Tracker.pluginProtos[a]=e;for(var h=0;h<ATInternet.Tracker.instances.length;h++)ATInternet.Tracker.instances[h].plugins.load(a,e)}};ATInternet.Tracker.delPlugin=function(a){if(ATInternet.Tracker.pluginProtos[a]){ATInternet.Tracker.pluginProtos[a]=void 0;for(var e=0;e<ATInternet.Tracker.instances.length;e++)ATInternet.Tracker.instances[e].plugins.unload(a)}};
ATInternet.Tracker.callbackProtos={};
}).call(window);;(function(){var dfltPluginCfg={"info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Clicks=function(a){var e=function(a){var b="";switch(a){case "exit":b="S";break;case "download":b="T";break;case "action":b="A";break;case "navigation":b="N"}return b},h=function(b){var e=b.name;a.exec("Utils","manageChapters",[b,"chapter",3],function(a){e=a+(e?e:"")});return e},b=function(b){var q={p:h(b),s2:b.level2||"",click:e(b.type)||""},l=a.getContext("page")||{};q.pclick=h(l);q.s2click=l.level2||"";b.customObject&&a.exec("Utils","customObjectToString",[b.customObject],
function(a){q.stc=a});a.sendHit(q,[["hitType",["click"]]],b.callback)};a.click={};a.clickListener=this.clickListener={};a.click.send=this.send=function(e){var h=!0;a.plugins.exec("TechClicks","manageClick",[e.elem,e.event],function(a){h=a});b(e);return h};a.clickListener.send=this.clickListener.send=function(e){if(e.elem){var h;a.plugins.exec("TechClicks","isFormSubmit",[e.elem],function(a){h=a?"submit":"click"});ATInternet.Utils.addEvtListener(e.elem,h,function(l){a.plugins.exec("TechClicks","manageClick",
[e.elem,l]);b(e)})}};a.click.set=this.set=function(b){a.dispatchSubscribe("click");a.setContext("click",{name:h(b),level2:b.level2||"",customObject:b.customObject});a.setParam("click",e(b.type)||"",{hitType:["click"]})};a.click.onDispatch=this.onDispatch=function(b){var e={hitType:["click"]};a.setParam("p",a.getContext("click").name,e);a.setParam("s2",a.getContext("click").level2,e);var l=a.getContext("click").customObject;l&&a.setParam("stc",l,{hitType:["click"],encode:!0});l=a.getContext("page")||
{};a.setParam("pclick",h(l),e);a.setParam("s2click",l.level2||"",e);a.sendHit(null,[["hitType",["click"]]],b);a.setContext("click",void 0)}};window.ATInternet.Tracker.addPlugin("Clicks");
}).call(window);;(function(){var dfltPluginCfg={"clientSideMode":"required","userIdCookieDuration":397,"userIdExpirationMode":"fixed","optOut":"OPT-OUT","userIdCookieName":"atuserid","optOutCookieName":"atoptedout","info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.ClientSideUserId=function(a){var e={},h=void 0,b=null,m=-1,q=!1;a.configPlugin("ClientSideUserId",dfltPluginCfg||{},function(a){e=a});var l=function(){h=a.getContext("userIdentifier");a.exec("Cookies","get",["atuserid"],function(a){b=a})},k=function(c,d,f){if("relative"===e.userIdExpirationMode||"fixed"===e.userIdExpirationMode&&null===b||f){var k=new Date;k.setTime(k.getTime()+864E5*e.userIdCookieDuration);a.exec("Cookies","set",[c,d,{end:k,path:"/"}]);a.exec("Cookies",
"get",[c,!0],function(c){f||d===c||a.setParam("idclient",d+"-NO",{permanent:!0,hitType:["all"]})})}},p=function(c,b,d){a.setParam("idclient",c,{permanent:!0,hitType:["all"]});k(d,c,b)},d=function(){var c=!1,b=null,d=ATInternet.Utils.optedOut;!1===d&&(a.exec("Cookies","set",["atoptedout",null,{path:"/"}]),a.getParam("idclient")===e.optOut&&a.delParam("idclient"));a.exec("Cookies","get",["atoptedout",!0],function(a){b=a});if(!0===d||b===e.optOut)c=!0;c&&(ATInternet.Utils.optedOut=!0);return c},c=function(){l();
var c,f=!1;if("required"===e.clientSideMode){if(c=navigator.userAgent,/Safari/.test(c)&&!/Chrome/.test(c)||/iPhone|iPod|iPad/.test(c))f=!0}else"always"===e.clientSideMode&&(f=!0);c=f;f="undefined"!==typeof h;q=d();if(c||f||q){var r="";c=!1;var k=e.userIdCookieName;q?(r=e.optOut,c=!0,k=e.optOutCookieName):a.getConfig("disableCookie")?(r=a.getParam("idclient"),c=!0):f?(r=h,c=!0):r=null!==b?b:ATInternet.Utils.uuid().v4();p(r,c,k)}a.emit("ClientSideUserId:Ready",{lvl:"INFO",details:{clientSideMode:e.clientSideMode,
userIdCookieDuration:e.userIdCookieDuration,userIdExpirationMode:e.userIdExpirationMode,userIdFromContext:h,userIdFromCookie:b,userId:r}})},f=function(a){a&&(a=a.detail)&&"clientsideuserid"===a.name&&a.id===m&&c()};(function(){a.plugins.waitForDependencies(["Cookies"],function(){var a=ATInternet.Utils.uuid();m=parseInt(a.num(8));ATInternet.Utils.removeOptOutEvent(f);ATInternet.Utils.addOptOutEvent(f,m);c()})})();a.clientSideUserId={};a.clientSideUserId.set=function(a){var c=e.userIdCookieName;q&&
(a=e.optOut,c=e.optOutCookieName);p(a,!0,c)}};window.ATInternet.Tracker.addPlugin("ClientSideUserId");
}).call(window);;(function(){var dfltPluginCfg={"domainAttribution":true,"info":true};var dfltGlobalCfg={"redirectionLifetime":30};window.ATInternet.Tracker.Plugins.ContextVariables=function(a){var e="",h=null,b,m="",q="",l={};a.configPlugin("ContextVariables",dfltPluginCfg||{},function(a){l=a});a.setConfig("redirectionLifetime",dfltGlobalCfg.redirectionLifetime,!0);var k=function(c,b,d){var r=null;a.plugins.exec(c,b,d,function(a){r=a});return r},p=function(a,c){return k("Utils",a,c)},d=function(c,b){var d=null;a.plugins.exec("Cookies",c,b,function(a){d=a});return d},c=function(){a.setParam("hl",function(){var a=new Date;return a.getHours()+
"x"+a.getMinutes()+"x"+a.getSeconds()},{permanent:!0,hitType:["all"]})};a.plugins.waitForDependencies(["Cookies","Utils"],function(){m="set"+(l.domainAttribution?"":"Private");q="get"+(l.domainAttribution?"":"Private");var f=p("getLocation",[]);e=p("getQueryStringValue",["xtref",f]);void 0===e&&(e="");b=a.getContext("forcedReferer");if(a.getConfig("redirect")){var f=p("getDocumentLevel",[]),f=b?b:null!==e?e:f.referrer||"acc_dir",g;if(g=f){g={path:"/",end:a.getConfig("redirectionLifetime")};var k=
d(q,["atredir"]);null!==k?g="object"===typeof k&&!(k instanceof Array):(d(m,["atredir",{},g]),g=!0)}g&&d(m,[["atredir","ref"],f])}else{h=d(q,[["atredir","ref"]]);d("del",[["atredir","ref"]]);a.setParam("vtag",a.version,{permanent:!0,hitType:["all"]});a.setParam("ptag","js",{permanent:!0,hitType:["all"]});f="";try{f+=window.screen.width+"x"+window.screen.height+"x"+window.screen.pixelDepth+"x"+window.screen.colorDepth}catch(r){}a.setParam("r",f,{permanent:!0,hitType:["all"]});f="";window.innerWidth?
f+=window.innerWidth+"x"+window.innerHeight:document.body&&document.body.offsetWidth&&(f+=document.body.offsetWidth+"x"+document.body.offsetHeight);a.setParam("re",f,{permanent:!0,hitType:["all"]});c();a.setParam("lng",navigator.language||navigator.userLanguage,{permanent:!0,hitType:["all"]});f=ATInternet.Utils.uuid().num(13);a.setParam("idp",f,{permanent:!0,hitType:["page","clickzone"]});a.setParam("jv",navigator.javaEnabled()?"1":"0",{hitType:["page"]});f=p("getDocumentLevel",[]);a.setParam("ref",
(b?b:"acc_dir"===e?"":null!==e?e:"acc_dir"===h?"":h?h:f.referrer).replace(/[<>]/g,"").substring(0,1600).replace(/&/g,"$"),{permanent:!0,last:!0,hitType:["page"]})}a.emit("ContextVariables:Ready",{lvl:"INFO"})})};window.ATInternet.Tracker.addPlugin("ContextVariables");
}).call(window);;(function(){var dfltPluginCfg={"info":false};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Cookies=function(a){var e={},h=this.getCookie=function(c){return!a.getConfig("disableCookie")&&c&&"string"===typeof c&&(c=RegExp("(?:^| )"+c+"=([^;]+)").exec(document.cookie)||null)?(c=c[1],c=a.getConfig("base64Storage")?ATInternet.Utils.Base64.decode(c):decodeURIComponent(c),c):null},b=this.setCookie=function(c,b,d){if(!a.getConfig("disableCookie")&&c&&"string"===typeof c&&"string"===typeof b){var f=a.getConfig("cookieDomain");c+="=";b=a.getConfig("base64Storage")?
ATInternet.Utils.Base64.encode(b):encodeURIComponent(b);b=c+b;c=!1;if(d){c=d.secure;var e=d.end,k=d.domain;d=d.path;e&&("function"===typeof e.toGMTString?b+=";expires="+e.toGMTString():"number"===typeof e&&(b+=";max-age="+e.toString()));k?b+=";domain="+k:f&&(b+=";domain="+f);d&&"string"===typeof d&&(b+=";path="+d)}f=a.getConfig("cookieSecure")||c;document.cookie=b+(f&&"boolean"===typeof f?";secure":"");return!0}return null},m=function(a){var c=null;(a=h(a))&&(c=ATInternet.Utils.jsonParse(a));return c},
q=function(a){return b(a.name,ATInternet.Utils.jsonSerialize(a),a.options)?a:null},l=function(a,c,b){var d=null;if(!b&&e[a])d=e[a];else if(d=m(a))d.options.session&&q(d),e[a]=d;return d?c?(a=null,!d||"object"!==typeof d.val||d.val instanceof Array||void 0===d.val[c]||(a=d.val[c]),a):d.val:null},k=function(a,c,b,d){var f=null;if(c){if(f=m(a))d=f,!d||"object"!==typeof d.val||d.val instanceof Array?f=null:(d.val[c]=b,f=d),f&&(f=q(f))}else c=d=d||{},d={},d.name=a,d.val=b,c.session&&"number"===typeof c.session&&
(c.end=c.session),d.options=c,f=q(d);f&&(e[a]=f);return f?f.val:null},p=function(a,c){c?k(a,c,void 0):(e[a]=void 0,b(a,"",{end:0}))};a.cookies={};var d=a.cookies.get=this.get=function(a,c){c=c||!1;return a instanceof Array&&2===a.length?l(a[0],a[1],c):l(a,void 0,c)};a.cookies.getPrivate=this.getPrivate=function(c,b){b=b||!1;c instanceof Array?c[0]+=a.getConfig("site"):c+=a.getConfig("site");return d(c,b)};var c=a.cookies.set=this.set=function(a,c,b){return a instanceof Array?k(a[0],a[1],c):k(a,null,
c,b)};a.cookies.setPrivate=this.setPrivate=function(b,d,f){b instanceof Array?b[0]+=a.getConfig("site"):b+=a.getConfig("site");return c(b,d,f)};var f=a.cookies.del=this.del=function(a){return a instanceof Array?p(a[0],a[1]):p(a)};a.cookies.delPrivate=this.delPrivate=function(c){c instanceof Array?c[0]+=a.getConfig("site"):c+=a.getConfig("site");return f(c)};a.cookies.cacheInvalidation=this.cacheInvalidation=function(){e={}}};window.ATInternet.Tracker.addPlugin("Cookies");
}).call(window);;(function(){var dfltPluginCfg={"info":true};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Page=function(a){var e=["pageId","chapterLabel","update"],h=["pid","pchap","pidt"],b=["page","site"],m=["f","x"],q=function(c){var b=c.name;a.exec("Utils","manageChapters",[c,"chapter",3],function(a){b=a+(b?b:"")});return b},l=function(a,c,b){c?a=c:a||"undefined"===typeof b||(a=b);return a},k=function(a,c,b){c.hasOwnProperty(b)&&(a[b]=l(a[b],c[b]))},p=function(c){if(!ATInternet.Utils.isPreview()||a.getConfig("preview"))ATInternet.Utils.isPrerender(function(a){c(a)})||
c()},d=function(c,d,f){if(d)for(var e=0;e<b.length;e++)if(d.hasOwnProperty(b[e])&&d[b[e]])for(var g in d[b[e]])d[b[e]].hasOwnProperty(g)&&(f?c[m[e]+g]=d[b[e]][g]:a.setParam(m[e]+g,d[b[e]][g]))},c=function(c,b,d){if(b){a.exec("Utils","manageChapters",[b,"chapter",3],function(a){a&&(b.chapterLabel=a.replace(/::$/gi,""))});for(var f=0;f<h.length;f++)b.hasOwnProperty(e[f])&&(d?c[h[f]]=b[e[f]]:a.setParam(h[f],b[e[f]]))}},f=function(c,b,d){if(b&&b.keywords instanceof Array){var f=b.keywords.length;if(0<
f){for(var e="",g=0;g<f;g++)e+="["+b.keywords[g]+"]"+(g<f-1?"|":"");d?c.tag=e:a.setParam("tag",e)}}},g=function(c,b,d){if(b){var f,e=function(a){return a?a:"0"};f=""+(e(b.category1)+"-");f+=e(b.category2)+"-";f+=e(b.category3);d?c.ptype=f:a.setParam("ptype",f)}},n=function(c,b,d){if(b)for(var f in b)b.hasOwnProperty(f)&&"undefined"!==typeof b[f]&&(d?c[f]=b[f]:a.setParam(f,b[f]))};a.customVars=this.customVars={};a.customVars.set=this.customVars.set=function(c){var b=a.getContext("page")||{},d=b.customVars;
if(d){if(c)for(var f in c)c.hasOwnProperty(f)&&(d[f]=ATInternet.Utils.completeFstLevelObj(d[f],c[f],!0))}else d=c;b.customVars=d;a.setContext("page",b)};a.dynamicLabel=this.dynamicLabel={};a.dynamicLabel.set=this.dynamicLabel.set=function(c){var b=a.getContext("page")||{};b.dynamicLabel=ATInternet.Utils.completeFstLevelObj(b.dynamicLabel,c,!0);a.setContext("page",b)};a.tags=this.tags={};a.tags.set=this.tags.set=function(c){var b=a.getContext("page")||{};b.tags=ATInternet.Utils.completeFstLevelObj(b.tags,
c,!0);a.setContext("page",b)};a.customTreeStructure=this.customTreeStructure={};a.customTreeStructure.set=this.customTreeStructure.set=function(c){var b=a.getContext("page")||{};b.customTreeStructure=ATInternet.Utils.completeFstLevelObj(b.customTreeStructure,c,!0);a.setContext("page",b)};a.page={};a.page.reset=this.reset=function(){a.setContext("page",void 0)};a.page.set=this.set=function(c){a.dispatchSubscribe("page");var b=a.getContext("page")||{};b.name=l(b.name,c.name,"");b.level2=l(b.level2,
c.level2,"");k(b,c,"chapter1");k(b,c,"chapter2");k(b,c,"chapter3");b.customObject=ATInternet.Utils.completeFstLevelObj(b.customObject,c.customObject,!0);a.setContext("page",b)};a.page.send=this.send=function(b){var e={p:q(b),s2:b.level2||""},h=!0,m=b.customObject;if(m){var s=a.getParam("stc",!0);if(s&&s.options.permanent){var v=s.options.hitType||[],x=ATInternet.Utils.arrayIndexOf;if(-1!==x(v,"page")||-1!==x(v,"all"))m=ATInternet.Utils.completeFstLevelObj(s.value||{},m,!0)}a.exec("Utils","customObjectToString",
[m],function(a){e.stc=a})}m=a.getContext("page")||{};m.vrn&&(e.vrn=m.vrn,m.vrn=void 0,a.setContext("page",m));s=a.getContext("InternalSearch")||{};"undefined"!=typeof s.keyword&&(e.mc=ATInternet.Utils.cloneSimpleObject(s.keyword),"undefined"!=typeof s.resultPageNumber&&(e.np=ATInternet.Utils.cloneSimpleObject(s.resultPageNumber)),a.setContext("InternalSearch",void 0));ATInternet.Utils.isPreview()&&a.getConfig("preview")&&(e.pvw=1);d(e,b.customVars,!0);c(e,b.dynamicLabel,!0);f(e,b.tags,!0);g(e,b.customTreeStructure,
!0);s=a.getContext("campaigns")||{};n(e,s,!0);a.setContext("campaigns",void 0);a.exec("TechClicks","manageClick",[b.elem,b.event],function(a){h=a});p(function(){a.sendHit(e,null,b.callback)});m.name=l(m.name,b.name,"");m.level2=l(m.level2,b.level2,"");k(m,b,"chapter1");k(m,b,"chapter2");k(m,b,"chapter3");a.setContext("page",m);return h};a.page.onDispatch=this.onDispatch=function(b){var e=a.getContext("page")||{},k=a.getContext("InternalSearch")||{};a.setParam("p",q(e));a.setParam("s2",e.level2||"");
e.vrn&&(a.setParam("vrn",e.vrn),e.vrn=void 0,a.setContext("page",e));"undefined"!=typeof k.keyword&&(a.setParam("mc",ATInternet.Utils.cloneSimpleObject(k.keyword)),"undefined"!=typeof k.resultPageNumber&&a.setParam("np",ATInternet.Utils.cloneSimpleObject(k.resultPageNumber)),a.setContext("InternalSearch",void 0));ATInternet.Utils.isPreview()&&a.getConfig("preview")&&a.setParam("pvw",1);d(null,e.customVars,!1);c(null,e.dynamicLabel,!1);f(null,e.tags,!1);g(null,e.customTreeStructure,!1);k=a.getContext("campaigns")||
{};n(null,k,!1);a.setContext("campaigns",void 0);var e=e.customObject,h=[["hitType",["page"]]];if(e)if(k=a.getParam("stc",!0)){var m=k.options.hitType||[],l=ATInternet.Utils.arrayIndexOf,l=-1!==l(m,"page")||-1!==l(m,"all"),m=k.options.permanent;l?(l=ATInternet.Utils.cloneSimpleObject(k),l.value=ATInternet.Utils.completeFstLevelObj(l.value||{},e,!0),a.setParam("stc",l.value,{encode:!0}),p(function(){a.sendHit(null,h,b)}),m&&a.setParam("stc",k.value,k.options)):(a.setParam("stc",e,{encode:!0}),p(function(){a.sendHit(null,
h,b)}),a.setParam("stc",k.value,k.options))}else a.setParam("stc",e,{encode:!0}),p(function(){a.sendHit(null,h,b)});else p(function(){a.sendHit(null,h,b)})}};window.ATInternet.Tracker.addPlugin("Page");
}).call(window);;(function(){var dfltPluginCfg={"clicksAutoManagementEnabled":true,"clicksAutoManagementTimeout":500,"info":false};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.TechClicks=function(a){var e,h;a.configPlugin("TechClicks",dfltPluginCfg||{},function(a){e=a.clicksAutoManagementEnabled;h=a.clicksAutoManagementTimeout});this.deactivateAutoManagement=function(){e=!1};var b=function(a){switch(a.target){case "_top":window.top.location.href=a.url;break;case "_parent":window.parent.location.href=a.url;break;default:window.location.href=a.url}},m=function(a){var c=a.timeout;a.mailto?setTimeout(function(){window.location.href=a.mailto},
c):a.form?setTimeout(function(){a.form.submit()},c):a.url&&setTimeout(function(){b({url:a.url,target:a.target})},c)},q=function(d){for(var c,e="_self",g=d.timeoutonly;d;){if(d.href&&0===d.href.indexOf("http")){c=d.href.split('"').join('\\"');e=d.target?d.target:e;break}d=d.parentNode}if(c){if(!g)a.onTrigger("Tracker:Hit:Sent:Ok",function(){b({url:c,target:e})});m({url:c,target:e,timeout:h})}},l=function(b){var c=b;for(b=c.timeoutonly;c&&"FORM"!==c.nodeName;)c=c.parentNode;if(c){if(!b)a.onTrigger("Tracker:Hit:Sent:Ok",
function(){c.submit()});m({form:c,timeout:h})}},k=function(b){var c=b;for(b=c.timeoutonly;c&&!(c.href&&0<=c.href.indexOf("mailto:"));)c=c.parentNode;if(c){if(!b)a.onTrigger("Tracker:Hit:Sent:Ok",function(){window.location.href=c.href});m({mailto:c.href,timeout:h})}},p=function(a){for(;a;){if(a.href){if(0<=a.href.indexOf("mailto:"))return"mailto";if(0===a.href.indexOf("http"))return"redirection"}else if("FORM"===a.nodeName)return"form";a=a.parentNode}return""};this.manageClick=function(a,b){var f=
!0;if(e&&a){var g;a:{for(g=a;g;){if("function"===typeof g.getAttribute&&("_blank"===g.getAttribute("target")||"no"===g.getAttribute("data-atclickmanagement"))){g=!0;break a}g=g.parentNode}g=a;for(var h=window.location.href,m;g;){if((m=g.href)&&0<=m.indexOf("#")&&h.substring(0,0<=h.indexOf("#")?h.indexOf("#"):h.length)===m.substring(0,m.indexOf("#"))){g=!0;break a}g=g.parentNode}g=!1}h=p(a);if(!g&&h)switch(h){case "mailto":k(a);f=!1;break;case "form":l(a);f=!1;break;case "redirection":q(a),f=!1}}b&&
(g=b.defaultPrevented,"function"===typeof b.isDefaultPrevented&&(g=b.isDefaultPrevented()),g||b.preventDefault&&b.preventDefault());return f}};window.ATInternet.Tracker.addPlugin("TechClicks");
}).call(window);;(function(){var dfltPluginCfg={"info":false};var dfltGlobalCfg={};window.ATInternet.Tracker.Plugins.Utils=function(a){var e=this,h={};e.getQueryStringValue=function(a,b){var e=window.ATInternet.Utils.hashcode(b).toString();if(!h[e]){h[e]={};var k=RegExp("[&#?]{1}([^&=#?]*)=([^&#]*)?","g"),p=k.exec(b);if(null!==p)for(;null!==p;)h[e][p[1]]=p[2],p=k.exec(b)}return h[e].hasOwnProperty(a)?h[e][a]:null};e.customObjectToString=function(a){return encodeURIComponent(window.ATInternet.Utils.jsonSerialize(a))};e.manageChapters=function(b,e,h){var k=a.getConfig("ignoreEmptyChapterValue"),
p="";if(b){h=parseInt(h,10);for(var d=1;d<h+1;d++)var c=b[e+d]||"",p=k?p+(c?c+"::":""):p+(b.hasOwnProperty(e+d)?c+"::":"")}return p};e.getDocumentLevel=function(){var b=a.getConfig("documentLevel");if(0>b.indexOf("."))return window[b]||document;b=b.split(".");return window[b[0]][b[1]]||document};e.getLocation=function(){return e.getDocumentLevel().location.href};a.dispatchIndex={};a.dispatchStack=[];a.dispatchEventFor={};var b=0;a.dispatchSubscribe=function(b){return a.dispatchIndex[b]?!1:(a.dispatchStack.push(b),
a.dispatchIndex[b]=!0)};a.dispatchSubscribed=function(b){return!0===a.dispatchIndex[b]};a.addSpecificDispatchEventFor=function(e){return a.dispatchEventFor[e]?!1:(a.dispatchEventFor[e]=!0,b++,!0)};a.processSpecificDispatchEventFor=function(e){a.dispatchEventFor[e]&&(a.dispatchEventFor[e]=!1,b--,0===b&&(a.dispatchEventFor={},a.emit("Tracker:Plugin:SpecificEvent:Exec:Complete",{lvl:"INFO"})))};a.dispatch=function(e){var h=function(){for(var b="",h=null;0<a.dispatchStack.length;)b=a.dispatchStack.pop(),
0===a.dispatchStack.length&&(h=e),a[b].onDispatch(h);a.dispatchIndex={};a.delContext(void 0,"customObject")},l=function(){if(a.plugins.isExecWaitingLazyloading())a.onTrigger("Tracker:Plugin:Lazyload:Exec:Complete",function(){h()},!0);else h()};if(0===b)l();else a.onTrigger("Tracker:Plugin:SpecificEvent:Exec:Complete",function(){l()},!0)};a.dispatchRedirect=function(b){var e=!0,h=null;b&&(b.elem&&(b.elem.timeoutonly=!0,a.plugins.exec("TechClicks","manageClick",[b.elem,b.event],function(a){e=a})),h=
b.callback);a.dispatch(h);return e}};window.ATInternet.Tracker.addPlugin("Utils");
}).call(window);
if(typeof window.ATInternet.onTrackerLoad==='function'){window.ATInternet.onTrackerLoad();}