
/**
  * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  * ! WARNING: This is a generated file, any modifications may be overwritten !
  * !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  *
  * Generated by "merge2file"
  *
  * Date: Thu Apr 04 2019 11:28:16 GMT+0200 (Central European Summer Time)
  * Export target: "/Users/dufourd/IdeaProjects/MPAT-github/MPAT-core/web/app/plugins/mpat-plugins/react_src/localization/merge/export/nl.js"
  * Executor: dufourd
  * Duration: 1 ms.
*/
const nl = {
  appMgr: {
    exclude: "Exclude",
    navModels: {
      slideflow: "Met de SlideFlow-navigatie kunt u als content creator volledige schermpagina's opmaken en de volgorde opgeven waarin ze worden gepresenteerd. De gebruikerservaring lijkt op het doorzoeken van een diapresentatie. <br />Hoewel pagina's selecteerbare HotSpots kunnen bevatten om extra inhoud en informatie te geven die betrekking heeft op de momenteel gepresenteerde pagina, is de navigatie tussen de afzonderlijke pagina's opeenvolgend, waardoor de content creator een verhaallijn kan vertellen.",
      timeline: "Event-based navigatie maakt het mogelijk om de presentatie van HbbTV-inhoud door het uitzendprogramma te laten leiden. Het meest voorkomende voorbeeld is de presentatie van de \"Rode Knop\" bij het begin van een TV-programma of advertentie om de kijker erop te attenderen dat er extra informatie beschikbaar is. Terwijl het uiterlijk van de knop meestal wordt geactiveerd door MPEG-stream gebeurtenissen kunnen alternatieve kanalen, bijv. Web sockets of applicatie pull-requests, ook gebruikt worden. <br/> Event-based navigatie is het beste geschikt voor kleine informatie-inserts.",
      website: "Dit model wordt meestal gebruikt voor HbbTV apps. Van een bestemmingspagina krijgen gebruikers toegang tot extra inhoud door op de schermknoppen te kiezen met de pijltjestoetsen - vergelijkbaar met een website. Vaak kunnen ook de snelkoppelingskleur- / numerieke toetsen worden gebruikt. <br /> Hoewel dit model gebruikelijk is, is het niet goed geschikt voor digitale verhalen, aangezien het gebruikerspad willekeurig is. Daarom moet elke pagina op zichzelf staan."
    }
  },
  navModel: {
    sampleApp: "Voorbeeld applicatie",
    components: "Componenten"
  },
  componentLoader: {
    containerTitle: {
      label: "Container stijlen"
    },
    fontSize: {
      label: "Lettertypegrootte",
      placeholder: "Grootte in px"
    },
    fontWeight: {
      label: "Tekst Gewicht",
      placeholder: "getal van 100 tot 900"
    },
    border: {
      label: "Rand",
      placeholder: "css border notation (e.g.: 1px solid #000)"
    },
    borderRadius: {
      label: "Randstraal",
      placeholder: "size in px"
    },
    margin: {
      label: "Margin",
      placeholder: "size in px"
    },
    padding: {
      label: "Padding",
      placeholder: "size in px"
    },
    color: {
      label: "Text Color"
    },
    backgroundColor: {
      label: "Achtergrond kleur"
    },
    lineHeight: {
      label: "Line Height",
      placeHolder: "Line height in px"
    }
  },
  formTypes: {
    fontSize: {
      label: "Font Size",
      placeholder: "14pt"
    },
    fontWeight: {
      label: "Tekst Gewicht",
      placeholder: "number form 100 to 900"
    },
    border: {
      label: "Rand",
      placeholder: "1px solid #000"
    },
    borderRadius: {
      label: "Randstraal",
      placeholder: "5px"
    },
    margin: {
      label: "Marge",
      placeholder: "0px"
    },
    padding: {
      label: "Vulling",
      placeholder: "0px"
    },
    color: {
      label: "Tekstkleur",
      placeholder: "notatie: rgb(), rgba(), # & kleur naam"
    },
    backgroundColor: {
      label: "Achtergrond kleur",
      placeholder: "notatie: rgb(), rgba(), # & kleur naam"
    }
  },
  componentStateSelector: {
    enter: "Zet in gang wanneer u op dit item drukt",
    focus: "Zet in gang wanneer het item is gericht",
    chooseAnAction: "Kies een actie",
    assetFinderPlaceholder: "Typ asset naam"
  },
  pageSelector: {
    loading: "LADEN",
    select: "KIES",
    noTitle: "geen titel",
    error: "FOUT"
  },
  styles: {
    choose: "Kies",
    typeUrlOrSelectMedia: "Typ url of selecteer media",
    ttSize: "Size in px, em, rem, pt, %",
    ttChoose: "Select the option you wish to use",
    ttImage: "Typme image url or choose from media library"
  },
  stylesPopup: {
    done: "Klaar"
  },
  textSubmit: {
    ok: "OK"
  },
  hotSpotEdit: {
    edit: "bewerk",
    title: "Hot Spot Pictogram",
    active: "Actief",
    background: "Achtergrond",
    icon: "Pictogram",
    orCustomFile: "Of aangepast bestand",
    focused: "gericht",
    normal: "normaal",
    iconColour: "Pictogram kleur",
    contentPosition: "Content Positie",
    location: "Locatie",
    overTheIcon: "Over het pictogram",
    underTheIcon: "Onder het pictogram",
    static: "Absoluut / statisch",
    staticContentPosition: "Statische content positie",
    top: "Boven",
    left: "Links",
    contentSize: "Content Grootte (px)",
    width: "Breedte",
    height: "Hoogte",
    ifEmptyFitContent: "Indien leeg, past het bij de content",
    keyBinding: "Key Binding",
    done: "Klaar",
    or: "OF",
    defaultIfAvailable: "Standaard, indien beschikbaar",
    customIcon: "Aangepast pictogram",
    choose: "Kies",
    selectRemoteButton: "Selecteer de afstandsbedieningsknop"
  },
  imageCropper: {
    cropRatio: "Uitsnijden afbeeldinging naar verhouding",
    cropImage: "Uitsnijden afbeeldinging",
    restore: "Herstellen",
    crop: "Uitsnijden",
    free: "Vrij",
    ttCropRatio: "Select crop ratio",
    ttCropImage: "[tooltip Crop image]",
    ttRestore: "Undo crop changes",
    ttCrop: "Crop to selection",
    ttFree: "[tooltip Free]"
  },
  layoutBuilder: {
    unused: "ongebruikt",
    returnToPageEditor: "TERUG NAAR DE PAGINA EDITOR",
    save: "BEWAREN",
    layoutBuilder: "Layout Builder",
    width: "Breedte",
    height: "Hoogte",
    left: "Links",
    top: "Boven",
    layoutTitle: "Layout Titel",
    placeholderTitle: "Voer hier de titel in",
    previewBackground: "Achtergrond Voorbeeld",
    placeholderBg: "TYP URL OF RGB",
    selectFile: "Kies bestand",
    addAnotherBox: "Voeg een andere box toe",
    add: "Toevoegen",
    showSafeArea: "Toon veilige zone",
    showGridLines: "Toon rasterlijnen",
    layoutUsedInPages: "Lay-out gebruikt in pagina's",
    ttDeleteThisBox: "Delete this box",
    ttPinBox: "Lock the location of this box",
    ttTitle: "Give this layout a title so you can easily identify it",
    ttPreviewBg: "Add a temporary background so you can align your layout",
    ttAddBox: "Add a box to the layout",
    ttSafeZone: "Toggle the border markings, which show the 'safe' internal area to place your boxes",
    ttGridLines: "Toggle the gridlines, which help you align your layout"
  },
  undoRedo: {
    undo: "ongedaan maken",
    redo: "overdoen"
  },
  gallery: {
    removeImage: "Verwijder afbeelding",
    gallerySettings: "Galerij instellingen",
    orientation: "oriëntering",
    horizontal: "Horizontaal",
    vertical: "Verticaal",
    imageCover: "Afbeeldingdeksel",
    zoomToFit: "Afbeeldinging passend aan container maken",
    autoPlay: "Automatisch afspelen",
    ms: "milliseconden",
    repeat: "Herhaal",
    loop: "Lus",
    useMediaKeys: "Gebruik MediaKey",
    dots: "Punten",
    arrows: "Pijlen",
    chooseImages: "Kies afbeeldingen",
    clearSelections: "Wis Selecties",
    noImages: "Geen afbeeldingen",
    closeCropEditor: "Close crop editor",
    ttOrient: "Which axis should the images scroll along",
    ttImageCover: "Zoom images to fit the container",
    ttAutoplay: "Auto play the images on page load after n milliseconds",
    ttRepeat: "Loop the images",
    ttUseMediaKeys: "Use the media keys on the controller to navigate the gallery",
    ttDots: "Show dots under/beside the gallery for navigation",
    ttArrows: "Show arrows to navigate the gallery",
    ttClear: "Clear the gallery images selections"
  },
  stateEditor: {
    title: "Component Bewerker",
    stateManagement: "Staatsmanagement",
    saveAsTemplate: "Sla op als sjabloon",
    txtToggleStateDisplay: "State",
    ttTitle: "[tooltip title]",
    phTitle: "Insert state title"
  },
  pageModelCreator: {
    chooseCustomBox: "Kies aanpasbare dozen",
    boxNb: "Doos Nr.",
    isItEditable: "Bewerkbaar",
    editableOrStyles: "Bewerkbare stijlen",
    addOrRemoveFromAllowedTypes: "Toevoegen of verwijderen van toegestane types",
    allowedTypes: "Toegestane typen",
    compontentTypeToAddOrRemove: "Component type om toe te voegen of te verwijderen",
    any: "Ieder",
    cancel: "Annuleer",
    create: "Creëren"
  },
  pageEditor: {
    title: "Pagina Editor",
    pageTitle: "Pagina titel",
    pageLink: "Pagina link",
    pageLayout: "Pagina Opmaak",
    pageParent: "Pagina Ouder",
    pageStyles: "Pagina Stijlen",
    pageBg: "Pagina achtergrond",
    scheduleUpdate: "Plan een update",
    unsavedChanges: "U heeft ongestoorde wijzigingen",
    untitled: "Onbeschreven",
    errorWhileSaving: "Fout bij het opslaan",
    confirmLeave: "U heeft ongestoorde wijzigingen, wilt u de pagina echt verlaten?",
    chooseBgColor: "Kies achtergrondkleur",
    show: "Laten zien",
    or: "of",
    movedToStyle: "Pagina achtergrondkleur en media zijn verplaatst naar pagina stijlen",
    createModelFromPage: "Maak model van pagina",
    changeStyles: "Verander stijlen",
    file: "Bestand",
    create: "Creër",
    pageFromModel: "Pagina gemaakt van Model",
    quickLink: "Snelle naar",
    ttQuickLink: "Shortcut to your other pages",
    saveModelInstance: "Opslaan model instance",
    savePage: "Bewaar pagina",
    duplicate: "Duplicaat",
    ttDuplicate: "Duplicate this page",
    editLayout: "Bewerk Opmaak",
    ttEditLayout: "Switch to edit layout",
    ttUndoRedo: "Undo/Redo your changes",
    ttSavePage: "Save your changes to this page",
    typeUrlOrRgb: "Type URL of RGB waarde",
    noParent: "Geen ouder",
    phTitle: "ENTER TITLE HERE",
    phBorderSize: "size in px",
    phFontSize: "size in px, em, rem, pt, %",
    descActiveComponent: "if no value is set, global settings defined in customizer are applied.",
    ttTitle: "Give this page a title so you can easily identify it",
    ttLayout: "Choose one of your layouts as a template for this page",
    ttParent: "Choose one of your other pages as  the parent for this page",
    ttLink: "Open in Firefox with FireHbbTV activated",
    titleDownloadFireHbbTV: "Download the firefox add-on for previewing HbbTV pages",
    titleDownloadFirefox: "Download Firefox to use the add-on to visualize HbbTV pages",
    ttToggleUpdate: "Schedule this update rather than going live immediately",
    ttPageStyles: "Edit the page and component CSS styles (colours, fonts, borders)",
    ttCreateModelFromPage: "Create a model based on this page",
    ttEditIcon: "Edit this component",
    ttToggleDefault: "Toggle this as the default selected component on page",
    ttBackToPageEditor: "[tooltip: go back to page editor]",
    ttToggleState: "[tooltip: toggle state management]"
  },
  componentEditor: {
    editComponentStyle: "Componentstijlen bewerken",
    editInner: "Bewerk...",
    titleComponentStyle: "Componentstijl",
    componentLabel: "Component Label",
    componentType: "Component Type",
    chooseView: "Kies weergave",
    hideFocus: "Focus verbergen",
    navigable: "bevaarbaar",
    scrollable: "Scrollable",
    hotSpot: "Hot Spot",
    companionScreen: "Companion Screen",
    thisIsAModel: "Dit is een model",
    editProtected: "Bewerking is uitgeschakeld",
    editStubborn: "Bewerk in ieder geval",
    ttLabel: "Add a label to identify this component",
    ttType: "Change the component type",
    ttView: "[tooltip choose view]",
    ttFocus: "Show/Hide whether this component has focus",
    ttHotSpot: "Is this component a 'Hot Spot'",
    ttNavigable: "Can the user navigate to this component",
    ttScrollable: "[tooltip component scrollable]",
    ttCompScr: "Is this component shown on a companion screen",
    ttEditStyle: "Edit how this component looks (borders, colours, fonts, margin, padding...)",
    ttTargetComponent: "[tooltip component target]"
  },
  chrome: {
    ttchromeFields: "[tooltip chrome fields]",
    ttSaturation: "[tooltip saturation - pick the saturation of chosen color]",
    ttHue: "[tooltip hue]",
    ttAlpha: "[tooltip alpha]"
  },
  audio: {
    title: "Geluidsinstellingen",
    audioUrlInput: "Bron bestand",
    audioUrlLabel: "Bron bestand",
    autoStart: "Automatische start",
    chooseFile: "Kies bestand",
    whenPageLoads: "Wanneer de pagina laadt",
    repeat: "Herhaal",
    loop: "Lus",
    ttAudioUrl: "Load audio from URL",
    ttChooseFile: "Select audio from disc or library",
    ttAutostart: "Play audio on page load when the page loads",
    ttRepeat: "Loop/Repeat audio"
  },
  broadcast: {
    notice1: "De broadcast component toont het uitzendingsignaal op de TV.",
    notice2: "Als u deze gebruikt op een desktopcomputer",
    notice3: "of verwant, zal de component zwart blijven."
  },
  clone: {
    choose: "Kies",
    modelComponentPage: "Model component pagina",
    layoutBox: "Opmaak doos",
    component: "Component",
    ttSelectModel: "Select the model/page that contains the component you want to clone",
    ttSelectComponent: "Select the component to clone",
    ttSourceLayout: "[tooltip source Layout]"
  },
  image: {
    title: "Beeldinstellingen",
    url: "Afbeelding URL",
    ttUrl: "Use a URL to fetch the image for this component",
    upload: "Afbeelding uploaden",
    ttUploadImg: "Upload an image for this component",
    chooseFromLibrary: "Of kies uit de bibliotheek",
    ttChooseImg: "Select an image from the library for this component",
    choose: "Kies"
  },
  launcher: {
    backend: {
      launcherSettings: "Launcher instellingen",
      toLinkAPage: "Als u wilt koppelen aan een specifieke pagina van dit onderdeel, voegt u het volgende toe aan uw link",
      launcherOrient: "Launcher Orientation",
      horizontal: "Horizontaal",
      vertical: "Verticaal",
      format: "Launcher-indeling",
      landscape: "Landschap",
      square: "Vierkant",
      squareWithInfo: "Vierkant met info",
      portrait: "Portret",
      launcherStyle: "Launcher stijl",
      optionStandard: "Standaard",
      optionArte: "Arte TV",
      scrollStyle: "Scroll stijl",
      optionCarousel: "Carrousel",
      optionPagination: "Paginering",
      paginationLoop: "Loop",
      showPaginationInfo: "Toon paginering info",
      addLauncherElement: "Launcher-element toevoegen",
      launcherThumbnail: "Launcher Thumbnail",
      launcherThumbnailUrl: "Launcher Thumbnail URL",
      chooseThumbnail: "Kies Thumbnail",
      title: "Titel",
      launcherTitle: "Launcher Titel",
      role: "Rol",
      link: "Link",
      controlTargetComponent: "Controle Doelcomponent",
      chooseTargetFirst: "Kies doel eerst!",
      launcherTargetUrl: "Launcher Doel URL",
      pages: "Paginas",
      state: "Staat",
      description: "Beschrijving",
      launcherDescription: "Launcher Beschrijving",
      deleteLauncherElement: "Verwijder Launcher Element",
      optionalContentIcon: "Optioneel inhouds icoon",
      none: "geen",
      audio: "audio",
      picture: "beeld",
      text: "tekst",
      video: "video",
      ttLauncherOrientation: "[tooltip launcher orientation]",
      ttElementFormat: "[tooltip elementFormat]",
      ttLauncherStyle: "[tooltip LauncherStyle]",
      ttScrollStyle: "[tooltip ScrollStyle]",
      ttShowPaginationInfo: "[tooltip ShowPaginationInfo]",
      ttColumnsRows: "[tooltip Columns and Rows]",
      ttAddLauncherElement: "[tooltip addLauncherElement]",
      ttThumbnailUrl: "[tooltip Launcher Thumbnail URL]",
      ttThumbnailChoose: "[tooltip LChoose Launcher Thumbnail]",
      ttTitle: "[tooltip title]",
      ttRole: "[tooltip ttRole]",
      ttUrl: "[tooltip Target Url]",
      ttPages: "[tooltip PageSelector]",
      ttComponent: "[tooltip ComponentStateSelector]",
      ttDescription: "[tooltip Description]",
      ttDeleteElement: "[tooltip deleteLauncherElement]",
      ttOptionalContentIcon: "[tooltip optionalContentIcon]",
      menuOrient: "Menu Oriëntatie"
    },
    frontend: {
      monthNames: [
        "JANUARI",
        "FEBRUARI",
        "MAART",
        "APRIL",
        "MEI",
        "JUNI",
        "JULI",
        "AUGUSTUS",
        "SEPTEMBER",
        "OCTOBER",
        "NOVEMBER",
        "DECEMBER"
      ],
      dayNames: [
        "ZONDAG",
        "MAANDAG",
        "DINSDAG",
        "WOENSDAG",
        "DONDERDAG",
        "VRIJDAG",
        "ZATERDAG"
      ]
    }
  },
  link: {
    linkSettings: "Link instellingen",
    linkImageUrl: "Link afbeelding URL",
    placeHolderLinkImageUrl: "Link afbeelding URL",
    ttLinkImageUrl: "[tooltip LINK IMAGE URL]",
    chooseLinkImage: "Kies link afbeelding",
    ttChooseLinkImage: "[tooltip Choose Link Image]",
    linkFocusedImageUrl: "Link Focused Image URL",
    placeHolderLinkFocusedImageUrl: "LINK FOCUSED IMAGE URL",
    ttLinkFocusedImageUrl: "[tooltip LINK FOCUSED IMAGE URL]",
    chooseLinkFocusedImage: "Choose Link Focused Image",
    ttChooseLinkFocusedImage: "[tooltip Choose Link Focused Image]",
    linkLabel: "Link Label",
    placeHolderLinkLabel: "LINK LABEL",
    ttLinkLabel: "[tooltip LINK LABEL]",
    or: "of",
    linkTarget: "Link doel",
    ttLinkTarget: "[tooltip Link Target]",
    placeHolderLinkUrl: "LINK URL",
    pages: "Paginas",
    ttPages: "[tooltip Pages]",
    imageLayoutCover: "Afbeelding opmaak omslag",
    ttImageLayoutCover: "[tooltip Image Layout Cover]"
  },
  list: {
    listSettings: "List Settings",
    addListElement: "Voeg lijstelement toe",
    ttAddListElement: "[tooltip Add List Element]",
    title: "Titel",
    ttTitle: "[tooltip Element Title]",
    placeHolderTitle: "ELEMENT TITEL",
    url: "URL",
    ttUrl: "[tooltip URL]",
    placeHolderUrl: "ELEMENT DOEL URL",
    description: "Beschrijving",
    ttDesc: "[tooltip ELEMENT DESCRIPTION]",
    placeHolderDesc: "ELEMENT BESCHRIJVING",
    deleteListElement: "Verwijder lijst element",
    ttDeleteListElement: "[tooltip Delete List Element]"
  },
  menu: {
    menuSettings: "Menu instellingen",
    addMenuItem: "Menu-item toevoegen",
    ttAddMenuItem: "[tooltip Add Menu item]",
    title: "Titel",
    ttTitle: "[tooltip title]",
    sideMenu: "Zijmenu",
    showAsSideMenu: "Toon menu als zijmenu",
    ttSideMenu: "Show menu as side menu",
    menuOrient: "Menu Oriëntatie",
    ttMenuOrient: "Menu Orientation",
    horizontal: "Horizontaal",
    vertical: "Verticaal",
    loop: "Lus",
    restart: "Of de navigatie opnieuw moet starten vanaf het eerste item na de laatste (en viceversa) of niet",
    ttLoop: "Whether the navigation should restart from first item after the last one ( and viceversa ) or not.",
    showButtons: "Toon knoppen",
    ttShowButtons: "Show Buttons",
    showRemoteKeys: "Toon afstandsbedieningen",
    ttShowRemoteKeys: "Show Remote Keys",
    selectAction: "Selecteer Actie",
    goToPrevPage: "Ga naar vorige pagina",
    toggleApplication: "Wissel applicatie (toon/verberg)",
    label: "Label",
    ttLabel: "[tooltip label]",
    placeHolderLabel: "MENU TEKST",
    remoteKey: "Afstandsknop",
    remoteControlKey: "Control afstandsknop",
    ttRemoteControlKey: "Remote control key",
    role: "Rol",
    ttRole: "[tooltip role]",
    link: "Link",
    controlApplication: "Controle Applicatie",
    controlTargetComponent: "Controle doelcomponent",
    launchAppViaAIT: "Start applicatie via AIT",
    url: "URL",
    placeHolderUrl: "TARGET URL",
    ttUrl: "Target url",
    pages: "Paginas",
    ttPages: "Pages",
    appId: "App ID",
    ttAppId: "App ID",
    fallbackUrl: "Terugval URL",
    ttFallbackUrl: "Fallback URL",
    appAction: "Applicatieactie",
    ttAppAction: "Application Action",
    state: "Staat",
    ttState: "[tooltip State]",
    addItem: "Voeg menu-item toe",
    ttAddItem: "Add menu item",
    deleteItem: "Verwijder menu-item",
    ttDeleteItem: "Delete menu item"
  },
  redbutton: {
    redButtonSettings: "Rode knop instellingen",
    buttonImage: "Knopbeeld",
    placeHolderImageUrl: "BEELD URL",
    ttImageUrl: "[tooltip IMAGE URL]",
    chooseImage: "Kies Beeld",
    ttChooseImage: "[tooltip Choose Image]",
    redButtonLink: "Roke knop link",
    placeHolderRedButtonLink: "LINK URL",
    ttRedButtonLink: "[tooltip redbutton LINK URL]",
    fadeInTime: "Vervagingstijd (s)",
    ttFadeInTime: "[tooltip Fade-in Time in seconds]",
    placeHolderFadeInTime: "SECONDEN",
    displayDuration: "Weergaveduur (s)",
    ttDisplayDuration: "[tooltip Display Duration in seconds]",
    placeHolderDisplayDuration: "SECONDEN"
  },
  scribbleLive: {
    noPreviewAvailable: "ScribleLive Feed. Geen specifiek voorbeeld beschikbaar.",
    title: "Scribble Live",
    hint1: "Hint: gebruik alstublieft",
    hint2: "voor taalinstellingen. (om informatie over timer-informatie weer te geven",
    hint3: "van een jaar geleden",
    ttFeedTitle: "[tooltip FeedTitle]",
    ttFeedId: "[tooltip FeedId]",
    ttFeedToken: "[tooltip FeedToken]",
    ttPolling: "[tooltip Polling]",
    ttFeedSize: "[tooltip FeedSize]"
  },
  scrolledText: {
    title: "Gescrolde tekst instellingen",
    arrowColor: "Pijlkleur",
    activeArrowColor: "Actieve pijl kleur",
    arrowPlacement: "Pijl Plaatsing",
    onText: "op tekst",
    left: "links",
    right: "rechts",
    aboveBelow: "boven/onder",
    outside: "buiten",
    noArrows: "geen pijlen",
    ttArrowColor: "[tooltip arrow color]",
    ttActiveArrowColor: "[tooltip active arrow color]",
    ttArrowPosition: "[tooltip arrow position]"
  },
  toggleTracking: {
    title: "De instellingen voor het volgen van de track aanpassen",
    enabledText: "Geactiveerde tekst",
    ttEnabledText: "[tooltip Enabled Text]",
    disabledText: "Uitgeschakelde tekst",
    ttDisabledText: "[tooltip Disabled Text]",
    button: "Knop",
    ttButton: "[tooltip Button]"
  },
  video: {
    title: "Video-instellingen",
    asset: "bezit",
    src: "Videobron",
    placeHolderSrc: "VIDEO URL",
    or: "of",
    chooseVideo: "Kies Video",
    thumbnail: "Video Thumbnail",
    placeHolderThumbnail: "THUMBNAIL URL",
    chooseThumbnail: "Kies Thumbnail",
    autoPlay: "Automatisch afspelen",
    startPlaybackWhenPage: "Begin afspelen als de pagina opent",
    repeat: "Herhaling",
    loop: "Lus",
    fullscreenStart: "Volledig scherm starten",
    startVideoFullScr: "Start video in fullscreen",
    removeBlackBars: "Verwijder zwarte balken",
    zoomVideo: "Zoem video in om zwwarte balken te verwijderen",
    playIcon: "Speel icoon",
    showPlayIcon: "Toon speel icoon wanneer de video klaar is",
    showNavBar: "Toon navigatiebalk",
    stopAfterDeselecting: "stop after focus was moved away"
  },
  timeline: {
    wizard: {
      title: "TimeLine Wizard",
      welcome: "Welcome to the timeline wizard. There are a few questions you need to answer to choose your version of timeline editor.",
      question: {
        videoType: "Do you want to use the broadcast video or an on-demand video ?",
        eventType: "Then which types of events do you intend to use ?",
        duration: "Then what is the duration of the show (in seconds, only important for video on demand) ?"
      },
      tooltip: {
        streamEvent: "for use with broadcast",
        mediaEvent: "only useful when a video-on-demand is present",
        keyEvent: "can be useful to remove elements added by stream or media events",
        timeEvent: "useful for splash screens and periodic logos",
        clockEvent: "useful for elements that need to appear at a certain clock based time"
      },
      timelineUI: {
        label: "Your TimeLine UI is",
        option: {
          vod: "On-demand Video UI",
          bc: "Broadcast UI",
          bcp: "Broadcast UI + Time",
          cui: "Complete UI"
        },
        timelineURL: "The URL of the Timeline application will be",
        next: "Next",
        errorSaving: "error saving option "
      }
    },
    title: "Tijdlijn",
    range: "Be; reik",
    duration: "Duur (sec)",
    fps: "Beelden per seconde",
    select_range: "Please select a range",
    editting_range: "Editting range {0}",
    no_selection: "No time range currently selected",
    new_project: "Nieuw projekt {0}",
    existing_project: "Herstellen mogelijk: Er bestaat reeds een projekt genaamd \"{0}\"",
    restore: {
      button: {
        value: "Herstellen"
      },
      wait: "Wacht {0} seconden.",
      skipload: " (laatste herstelling was {0} seconden geleden om {1})",
      scenario_loaded: "Scenario voor {0} met {1} evenementen publiceerd om {2}",
      nothing_to_restore: "Niets te herstellen",
      restored: "{0} gerestaureerde evenementen.",
      no_overwrite: "Behoudt van huidige werkomgeving",
      ask_to_overwrite: "Huidige werkomgeving overschrijven?"
    },
    publish: {
      button: {
        value: "Publiceren"
      },
      publishing: "Publicatie...",
      no_ovewrite: "Publicatie wordt overgeslagen om gegevensverlies te voorkomen",
      warning_overwrite: "WAARSCHUWING:\nDit zal uw huidige scenario voor '{0}' overschrijven.\n\nVerder met het publiceren?",
      wait: "Wacht {0} seconden.",
      saved: " (bewaard {0}s geleden om {1})",
      notsaving: "Niet bewaren: Scenario is leeg",
      scenario_published: "{0} scenario met {1} event(s) is gepubliceerd om {2}"
    },
    remove: {
      button: {
        value: "Publiceren"
      },
      deleting: "Publicatie...",
      no_ovewrite: "Publicatie wordt overgeslagen om gegevensverlies te voorkomen",
      warning_overwrite: "WAARSCHUWING:\nDit zal uw huidige scenario voor '{0}' overschrijven.\n\nVerder met het publiceren?",
      wait: "Wacht {0} seconden.",
      saved: " (bewaard {0}s geleden om {1})",
      notsaving: "Niet bewaren: Scenario is leeg",
      scenario_deleted: "{0} scenario met {1} event(s) is gepubliceerd om {2}"
    },
    rangeEdit: {
      button: {
        value: "Maak bewerkbaar",
        title: "Ververs en/of maak het tijdsbestek bewerkbaar"
      },
      button2: {
        value: "Wissel selecties",
        title: "Wissel het geselecteerde tijdsbestek met degene rechts"
      },
      event: {
        type: "Type",
        keycode: "KeyCode",
        data: "Data",
        begin: "Begin",
        dura: "Duur"
      },
      eventOptions: {
        streamEvent: "StreamEvent",
        keyEvent: "KeyEvent",
        mediaEvent: "MediaEvent",
        timeEvent: "TimeEvent",
        clockEvent: "ClockEvent"
      },
      time: "Tijd",
      page: "Pagina"
    },
    rangeRemove: {
      button: {
        value: "Verwijder selectie",
        title: "Verwijder het geselecteerde tijdsbestek"
      }
    },
    rangeTool: {
      range: "Evenementen bewerken",
      swapButton: {
        value: "Wissel",
        title: "Wissel geselecteerd bereik naast rechts"
      }
    },
    restoreButton: {
      error: "Fout bij het laden van het scenario"
    },
    timelineEditor: {
      error: {
        unableToSet: "Waarschuwing: niet in staat om waarde in te stellen"
      },
      unsavedChanges: "You have unsaved changes"
    },
    dsmcc: {
      title: "DSMCC Events XML generator",
      button: {
        download: {
          link: "Download",
          title: "Retrieve a DSMCC formatted XML for stream events"
        },
        save: {
          link: "Save",
          title: "Save the DSMCC settings"
        },
        link: "DSMCC",
        title: "Download een DSMCC geformatteerde XML voor stream events"
      },
      fileName: "dsmcc.xml",
      seID: {
        label: "StreamEvent ID",
        title: "StreamEvent ID (1-65535)"
      },
      seName: {
        label: "StreamEvent Naam",
        title: "StreamEvent Naam (TXT)"
      },
      seComponentTag: {
        label: "Component Tag",
        title: "Component Tag (1-255)"
      },
      labelUrl: "URL",
      error: {
        onLoad: "Error getting DSMCC option, modify values and try again",
        onSave: "Error saving DSMCC option"
      },
      saved: "DSMCC info saved"
    },
    elementMenu: {
      noFreeSpace: "no free space",
      enterKeyCode: "Enter keycode",
      addToTheTimeline: "Add to the timeline",
      back: "Back",
      addAPage: "Add a page",
      inTheBack: "In the back",
      backPage: "Back page",
      remove: "Remove",
      addEventLinkToPage: "Add an event linking to a page",
      abbr: {
        streamEvent: "StreamEv",
        keyEvent: "KeyEv",
        mediaEvent: "MediaEv",
        timeEvent: "TimeEv",
        clockEvent: "ClockEv"
      },
      targetPage: "Target Page",
      addElement: "Add element"
    }
  },
  frontend: {
    error: {
      title: "Error",
      formatNotSupported: "Audio/Video formaat wordt niet ondersteund",
      connection: "Kan geen verbinding maken met de server of de verbinding die is verloren",
      unidentified: "Niet geïdentificeerde fout",
      resource: "Onvoldoende middelen",
      corrupt: "Inhoud corrupt of ongeldig",
      available: "Inhoud niet beschikbaar",
      positition: "Inhoud niet beschikbaar op een bepaalde positie",
      blocked: "Inhoud niet beschikbaar als gevolg van ouderlijke controle"
    },
    state: {
      stopped: "GESTOPT",
      playing: "SPELEN",
      paused: "GEPAUZEERD",
      connected: "VERBINDING",
      buffering: "BUFFERING",
      finished: "BEËINDIGD"
    },
    video360: {
      deviceNotSupported: "Uw apparaat wordt niet ondersteund.",
      errSyncPlayPos: "Sync of current playPosition already reported. It seems that the player is not playing",
      errInvJson: "get invalid json from server",
      errConfig: "invalid config object. at least config.gatewayUrl must be set.",
      error: "Fout"
    }
  }
};
module.exports = nl;